spring:
  application:
    name: sfg-springai-functions
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-4o
sfg:
  api:
    api-ninjas-key: ${APININJAS_KEY}
    weather-service-url: https://api.api-ninjas.com/v1/weather
    geo-service-url: https://geocoding-api.open-meteo.com/v1/
kind: Application
